name: workflow-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write 

env:
  CSV_URL: "MLproject/banking-data_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check Env Variables
      - name: Check Env
        run: echo $CSV_URL

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLproject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false
          
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate mlflow-env
          mlflow run MLproject --env-manager=local

      - name: Get latest run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # Get latest run_id
      - name: Get latest run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
     
      # Copy model artifacts
      - name: Copy model artifacts to models/
        run: |
          mkdir -p models/
          cp -r mlruns/0/$RUN_ID/artifacts/model models/
          
      # Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add -f models/
          git commit -m "Save trained model artifacts" || true
          git pull --rebase origin main 
          git push origin main

      # Build Docker Image from MLflow Model
      - name: Build Docker Image from MLflow Model
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate mlflow-env
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name workflow-ci
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag workflow-ci ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest
